# PostgreSQL Configuration (Production)
spring.datasource.url=jdbc:postgresql://localhost:5432/grimoire_vault
spring.datasource.username=postgres
spring.datasource.password=secret
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Flyway/Liquibase will handle schema in prod, so we set this to validate or none
spring.jpa.hibernate.ddl-auto=validate
